services:
  dev:
    container_name: guardian_dev
    image: ocaml/opam:debian-12-ocaml-5.3
    volumes:
      # default user is "opam"
      - ..:/workspace:cached
      - opam:/home/opam/.opam:cached
      - build:/workspace/_build:cached
      - db:/databases/dev/:ro
      - ${HOME}/.claude:/home/opam/.claude
    depends_on: [database]
    ports: [3020:3000]
    command: sleep infinity

  database:
    container_name: guardian_database
    image: mariadb:10.6.3
    command: --max_allowed_packet=629145600
    ports: [3320:3306]
    environment:
      - TZ=Europe/Zurich
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=development
      - MYSQL_USER=root
    volumes:
      - db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/:ro

  adminer:
    image: adminer:standalone
    restart: always
    ports: [8080:8080]
    depends_on: [database]

volumes:
  opam:
  build:
  db:
